### ISSUE TITLE
Do you want to write a Sample about't it.

### ISSUE THREAD

**Issue by NicodeLee** [79144876/android-async-http-loopj-with-cache#1]
I can not see any demo about this Project.
Thantks.

**Comment by liufsd** [comment]
Okay! I will create demo project and then push it .

**Comment by liufsd** [comment]
push here.https://github.com/79144876/android-async-http-loopj-with-cache/commit/0b0353c0f8f77362553f2299637b48feb657e4f7 you can clone it.
